### ISSUE TITLE
Wrong home directory

### ISSUE THREAD

**Issue by hmlendea** [trizen/alsi#11]
On a fresh install of Arch Linux for ARM I get the folowing error:

`[!] There is a problem with the COLORS_FILE '/home/alarm/.config/alsi/alsi.colors': No such file or directory`

I've renamed the `alarm` user to something else but alsi seems to still be looking for `alarm`
I've checked in all places and the user seems to have been reamed correctly.

I think it must be something that I missed though, because I configured 2 Raspberry Pis and only one of them has this issue. What environment variables does alsi use? $HOME and $USER are both set correctly to the new username.

**Comment by trizen** [comment]
Either delete the directory `~/.config/alsi` or edit the paths in the configuration file `~/.config/alsi/alsi.conf`.

**Comment by hmlendea** [comment]
Thanks. The conf file seems to have had a lot of paths pointing to the old home directory. Deleting it as suggested solved the problem.
