### ISSUE TITLE
Doesn't detect my WM even though it's in alsi.wm

### ISSUE THREAD

**Issue by Sweenu** [trizen/alsi#5]
I use qtile and it is in the alsi.wm by default. However, alsi shows `Window Manager: Unknown`

**Comment by trizen** [comment]
What is the output of `ps -A |  grep qtile`?

**Comment by Sweenu** [comment]
```
$ ps -A | grep qtile
1212 ?        00:01:55 qtile
```

Could it be because Lightdm is the parent process of qtile?

**Comment by trizen** [comment]
Looks good and I don't think it should matter as long as there is a process name that `alsi` can recognize (in this case `qtile`).

Make sure, however, that the value of `PS_COMMAND` in `~/.config/alsi/alsi.conf` is set to `"ps -A"`.

**Comment by Sweenu** [comment]
Alright, I figured it out. The command outputs qtile when I first start it. But as soon as I restart qtile, the process name changes to python instead. That's why it wasn't working.

I'll probably just open up an issue on the qtile repo instead.
